### PR TITLE
Support for 'configure_requires'

### PR DESCRIPTION
**Pull request by kenneth-olwing**
Add keyword to include the 'configure_requires' yaml section in
the dependencies.

### CODE REVIEW

**Comment by DrHyde** [comment]
Thanks! Looks like the test failures are just Travis being silly, so I'll merge and get a new release out.

**Comment by DrHyde** [comment]
Version 2.49 is on its way to the CPAN

**Comment by kenneth-olwing** [comment]
That was quick! Thanks, and have a good one :-)

ken1

**Comment by davidcantrelluk2** [comment]
This one got done quickly because it was simple, Obviously Correct, and came with tests. If you're using this regularly then you may feel like also addressing https://github.com/DrHyde/perl-modules-CPAN-FindDependencies/issues/7 :-)

**Pull request merged**
